/*
    Multiple Comments

    # - Pre-Processor
    include
    Directive/Directory/Predefined Library
    iostream.h: header file : input / output stream (flow of data)
    conio.h: header file: console input / output

*/

//Pre-Processor Directive
#include<iostream.h>
#include<conio.h>

//cout<<"Brain Mentors"<<endl;
//main(): entry point or intial of every c++ program
//void - null or empty
void main()
{
	clrscr(); // clear screen
	cout<<"Hello World"<<endl;
//        cout: console output: print the output on output screen
//          endl: end line or new line
	getch(); // get character
//	return 0;
}